"""! Colors used throughout the UI """

UI_BACKGROUND_COLOR = "#0d1117"
UI_BLOCK_RANDOM_VIDEO_COLOR = "#c6cdd5"
UI_BLOCK_NORMAL_VIDEO_COLOR = "#89929b"
UI_BLOCK_SELECTED_VIDEO_FRAME_COLOR = "#77bdfb"
UI_BLOCK_USED_VIDEO_FRAME_COLOR = "#21262d"
UI_BLOCK_PLAYED_VIDEO_COLOR = "#161b22"
